### ISSUE TITLE
JVM is terminating. Shutting down Jettyissue title

### ISSUE THREAD

**Issue by rnkhouse** [jenkinsci/helm-charts#120]
**Describe the bug**
I am getting **JVM is terminating. Shutting down Jetty** error suddenly.

**Version of Helm and Kubernetes**:
Helm Version:

```console
$ helm version
Client: &version.Version{SemVer:"v2.17.0", GitCommit:"a690bad98af45b015bd3da1a41f6218b1a451dbe", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.17.0", GitCommit:"a690bad98af45b015bd3da1a41f6218b1a451dbe", GitTreeState:"clean"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-14T00:06:38Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Helm chart version**
jenkins-2.15.1

**What you expected to happen**:
It should deploy jenkins successfully.

**Anything else we need to know**:
2020-11-02 17:47:48.742+0000 [id=27]	INFO	jenkins.InitReactorRunner$1#onAttained: Started initialization
2020-11-02 17:47:54.107+0000 [id=27]	INFO	jenkins.InitReactorRunner$1#onAttained: Listed all plugins
2020-11-02 17:48:53.492+0000 [id=27]	INFO	jenkins.InitReactorRunner$1#onAttained: Prepared all plugins
2020-11-02 17:48:56.396+0000 [id=26]	INFO	jenkins.InitReactorRunner$1#onAttained: Started all plugins

2020-11-02 17:49:12.727+0000 [id=26]	INFO	jenkins.InitReactorRunner$1#onAttained: Augmented all extensions
2020-11-02 17:49:13.899+0000 [id=26]	INFO	jenkins.model.Jenkins#setBuildsAndWorkspacesDir: Using non default workspaces directories: ${JENKINS_HOME}/workspace/${ITEM_FULLNAME}.
2020-11-02 17:49:14.761+0000 [id=27]	INFO	jenkins.InitReactorRunner$1#onAttained: System config loaded
2020-11-02 17:49:28.805+0000 [id=22]	INFO	winstone.Logger#logInternal: JVM is terminating. Shutting down Jetty
Unable to obtain resource from /var/jenkins_home/plugins/workflow-support/WEB-INF/lib/jboss-marshalling-2.0.6.Final.jar:
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686)
	at java.util.zip.ZipFile.getEntry(ZipFile.java:315)
	at java.util.jar.JarFile.getEntry(JarFile.java:240)
	at java.util.jar.JarFile.getJarEntry(JarFile.java:223)
	at jenkins.util.AntClassLoader.storeAndConvert(AntClassLoader.java:788)
	at jenkins.util.AntClassLoader.getResourceURL(AntClassLoader.java:1033)
	at jenkins.util.AntClassLoader.getUrl(AntClassLoader.java:930)
	at jenkins.util.AntWithFindResourceClassLoader.findResource(AntWithFindResourceClassLoader.java:43)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at jenkins.ClassLoaderReflectionToolkit.invoke(ClassLoaderReflectionToolkit.java:44)
	at jenkins.ClassLoaderReflectionToolkit._findResource(ClassLoaderReflectionToolkit.java:90)
	at hudson.ClassicPluginStrategy$DependencyClassLoader.findResource(ClassicPluginStrategy.java:685)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1090)
	at jenkins.util.AntClassLoader.getResource(AntClassLoader.java:893)
	at hudson.model.Descriptor.getViewPage(Descriptor.java:856)
	at hudson.model.Descriptor.getGlobalConfigPage(Descriptor.java:820)
	at io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator.lambda$describe$1(GlobalConfigurationCategoryConfigurator.java:86)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator.describe(GlobalConfigurationCategoryConfigurator.java:90)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:300)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:287)
	at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$8(ConfigurationAsCode.java:755)
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:691)
	at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:755)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:740)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:616)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:298)
	at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:290)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

***

2020-11-02 18:07:30.219+0000 [id=28]	INFO	jenkins.InitReactorRunner$1#onAttained: Started initialization
2020-11-02 18:07:37.691+0000 [id=27]	INFO	jenkins.InitReactorRunner$1#onAttained: Listed all plugins
2020-11-02 18:08:39.798+0000 [id=28]	INFO	jenkins.InitReactorRunner$1#onAttained: Prepared all plugins
2020-11-02 18:08:45.577+0000 [id=27]	INFO	jenkins.InitReactorRunner$1#onAttained: Started all plugins
2020-11-02 18:09:03.099+0000 [id=28]	INFO	jenkins.InitReactorRunner$1#onAttained: Augmented all extensions
2020-11-02 18:09:05.071+0000 [id=27]	INFO	jenkins.model.Jenkins#setBuildsAndWorkspacesDir: Using non default workspaces directories: ${JENKINS_HOME}/workspace/${ITEM_FULLNAME}.
2020-11-02 18:09:05.390+0000 [id=27]	INFO	jenkins.InitReactorRunner$1#onAttained: System config loaded

breaking container after this point...

***

kubectl logs jenkins-6d67b7d599-g26mg jenkins -f
Running from: /usr/share/jenkins/jenkins.war
webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
2020-11-02 18:20:03.800+0000 [id=1]	INFO	org.eclipse.jetty.util.log.Log#initialized: Logging initialized @2766ms to org.eclipse.jetty.util.log.JavaUtilLog
2020-11-02 18:20:05.501+0000 [id=1]	INFO	winstone.Logger#logInternal: Beginning extraction from war file
2020-11-02 18:20:05.620+0000 [id=1]	WARNING	o.e.j.s.handler.ContextHandler#setContextPath: Empty contextPath
2020-11-02 18:20:05.930+0000 [id=1]	INFO	org.eclipse.jetty.server.Server#doStart: jetty-9.4.33.v20201020; built: 2020-10-20T23:39:24.803Z; git: 1be68755656cef678b79a2ef1c2ebbca99e25420; jvm 1.8.0_242-b08
2020-11-02 18:20:08.004+0000 [id=1]	INFO	o.e.j.w.StandardDescriptorProcessor#visitServlet: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
2020-11-02 18:20:08.441+0000 [id=1]	INFO	o.e.j.s.s.DefaultSessionIdManager#doStart: DefaultSessionIdManager workerName=node0
2020-11-02 18:20:08.442+0000 [id=1]	INFO	o.e.j.s.s.DefaultSessionIdManager#doStart: No SessionScavenger set, using defaults
2020-11-02 18:20:08.444+0000 [id=1]	INFO	o.e.j.server.session.HouseKeeper#startScavenging: node0 Scavenging every 600000ms
2020-11-02 18:20:10.597+0000 [id=1]	INFO	hudson.WebAppMain#contextInitialized: Jenkins home directory: /var/jenkins_home found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
2020-11-02 18:20:11.189+0000 [id=1]	INFO	o.e.j.s.handler.ContextHandler#doStart: Started w.@5f9edf14{Jenkins v2.264,/,file:///var/jenkins_home/war/,AVAILABLE}{/var/jenkins_home/war}
2020-11-02 18:20:11.293+0000 [id=1]	INFO	o.e.j.server.AbstractConnector#doStart: Started ServerConnector@366e2eef{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2020-11-02 18:20:11.297+0000 [id=1]	INFO	org.eclipse.jetty.server.Server#doStart: Started @10261ms
2020-11-02 18:20:11.298+0000 [id=21]	INFO	winstone.Logger#logInternal: Winstone Servlet Engine running: controlPort=disabled
2020-11-02 18:20:16.325+0000 [id=27]	INFO	jenkins.InitReactorRunner$1#onAttained: Started initialization
2020-11-02 18:20:22.081+0000 [id=26]	INFO	jenkins.InitReactorRunner$1#onAttained: Listed all plugins
2020-11-02 18:21:22.986+0000 [id=27]	INFO	jenkins.InitReactorRunner$1#onAttained: Prepared all plugins
2020-11-02 18:21:25.388+0000 [id=27]	INFO	jenkins.InitReactorRunner$1#onAttained: Started all plugins
2020-11-02 18:21:46.723+0000 [id=27]	INFO	jenkins.InitReactorRunner$1#onAttained: Augmented all extensions
2020-11-02 18:21:47.508+0000 [id=26]	INFO	jenkins.model.Jenkins#setBuildsAndWorkspacesDir: Using non default workspaces directories: ${JENKINS_HOME}/workspace/${ITEM_FULLNAME}.
2020-11-02 18:21:47.886+0000 [id=27]	INFO	jenkins.InitReactorRunner$1#onAttained: System config loaded
2020-11-02 18:21:59.296+0000 [id=22]	INFO	winstone.Logger#logInternal: JVM is terminating. Shutting down Jetty
Unable to obtain resource from /var/jenkins_home/plugins/configuration-as-code/WEB-INF/lib/vavr-0.10.3.jar:
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686)
	at java.util.zip.ZipFile.getEntry(ZipFile.java:315)
	at java.util.jar.JarFile.getEntry(JarFile.java:240)
	at java.util.jar.JarFile.getJarEntry(JarFile.java:223)
	at jenkins.util.AntClassLoader.storeAndConvert(AntClassLoader.java:788)
	at jenkins.util.AntClassLoader.getResourceURL(AntClassLoader.java:1033)
	at jenkins.util.AntClassLoader.getUrl(AntClassLoader.java:930)
	at jenkins.util.AntWithFindResourceClassLoader.findResource(AntWithFindResourceClassLoader.java:43)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at jenkins.ClassLoaderReflectionToolkit.invoke(ClassLoaderReflectionToolkit.java:44)
	at jenkins.ClassLoaderReflectionToolkit._findResource(ClassLoaderReflectionToolkit.java:90)
	at hudson.ClassicPluginStrategy$DependencyClassLoader.findResource(ClassicPluginStrategy.java:685)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1090)
	at jenkins.util.AntClassLoader.getResource(AntClassLoader.java:893)
	at hudson.model.Descriptor.getViewPage(Descriptor.java:856)
	at hudson.model.Descriptor.getGlobalConfigPage(Descriptor.java:820)
	at io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator.lambda$describe$1(GlobalConfigurationCategoryConfigurator.java:86)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator.describe(GlobalConfigurationCategoryConfigurator.java:90)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:300)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:287)
	at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$8(ConfigurationAsCode.java:755)
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:691)
	at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:755)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:740)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:616)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:298)
	at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:290)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Unable to obtain resource from /var/jenkins_home/plugins/git-client/WEB-INF/lib/org.eclipse.jgit.http.server-5.9.0.202009080501-r.jar:
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686)
	at java.util.zip.ZipFile.getEntry(ZipFile.java:315)
	at java.util.jar.JarFile.getEntry(JarFile.java:240)
	at java.util.jar.JarFile.getJarEntry(JarFile.java:223)
	at jenkins.util.AntClassLoader.storeAndConvert(AntClassLoader.java:788)
	at jenkins.util.AntClassLoader.getResourceURL(AntClassLoader.java:1033)
	at jenkins.util.AntClassLoader.getUrl(AntClassLoader.java:930)
	at jenkins.util.AntWithFindResourceClassLoader.findResource(AntWithFindResourceClassLoader.java:43)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at jenkins.ClassLoaderReflectionToolkit.invoke(ClassLoaderReflectionToolkit.java:44)
	at jenkins.ClassLoaderReflectionToolkit._findResource(ClassLoaderReflectionToolkit.java:90)
	at hudson.ClassicPluginStrategy$DependencyClassLoader.findResource(ClassicPluginStrategy.java:685)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1090)
	at jenkins.util.AntClassLoader.getResource(AntClassLoader.java:893)
	at hudson.model.Descriptor.getViewPage(Descriptor.java:856)
	at hudson.model.Descriptor.getGlobalConfigPage(Descriptor.java:820)
	at io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator.lambda$describe$1(GlobalConfigurationCategoryConfigurator.java:86)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at io.jenkins.plugins.casc.impl.configurators.GlobalConfigurationCategoryConfigurator.describe(GlobalConfigurationCategoryConfigurator.java:90)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:300)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:287)
	at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$8(ConfigurationAsCode.java:755)
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:691)
	at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:755)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:740)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:616)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:298)
	at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:290)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

breaking after this point...

**Comment by torstenwalter** [comment]
Did you check Kubernetes events? Did a livemess probe fail which could have triggered this?

**Comment by rnkhouse** [comment]
@torstenwalter  Thanks for the prompt response. I see below logs in kubernetes:

  Warning  Unhealthy               3m41s (x2 over 3m48s)  kubelet                  Readiness probe failed: HTTP probe failed with statuscode: 503
  Warning  Unhealthy               66s                    kubelet                  Readiness probe failed: Get http://10.2.0.75:8080/login: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

**Comment by torstenwalter** [comment]
I think that #121 could help resolving this.

**Comment by rnkhouse** [comment]
Thanks. For now, I just fixed using the below settings:

    master:
        healthProbeLivenessInitialDelay: 180
        healthProbeReadinessInitialDelay: 120

**Comment by rnkhouse** [comment]
It's happening again. This is very inconsistent:

Running from: /usr/share/jenkins/jenkins.war
webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
2020-11-06 19:58:07.771+0000 [id=1]	INFO	org.eclipse.jetty.util.log.Log#initialized: Logging initialized @2184ms to org.eclipse.jetty.util.log.JavaUtilLog
2020-11-06 19:58:08.833+0000 [id=1]	INFO	winstone.Logger#logInternal: Beginning extraction from war file
2020-11-06 19:58:08.899+0000 [id=1]	WARNING	o.e.j.s.handler.ContextHandler#setContextPath: Empty contextPath
2020-11-06 19:58:09.196+0000 [id=1]	INFO	org.eclipse.jetty.server.Server#doStart: jetty-9.4.33.v20201020; built: 2020-10-20T23:39:24.803Z; git: 1be68755656cef678b79a2ef1c2ebbca99e25420; jvm 1.8.0_242-b08
2020-11-06 19:58:11.598+0000 [id=1]	INFO	o.e.j.w.StandardDescriptorProcessor#visitServlet: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
2020-11-06 19:58:12.296+0000 [id=1]	INFO	o.e.j.s.s.DefaultSessionIdManager#doStart: DefaultSessionIdManager workerName=node0
2020-11-06 19:58:12.297+0000 [id=1]	INFO	o.e.j.s.s.DefaultSessionIdManager#doStart: No SessionScavenger set, using defaults
2020-11-06 19:58:12.298+0000 [id=1]	INFO	o.e.j.server.session.HouseKeeper#startScavenging: node0 Scavenging every 660000ms
2020-11-06 19:58:15.094+0000 [id=1]	INFO	hudson.WebAppMain#contextInitialized: Jenkins home directory: /var/jenkins_home found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
2020-11-06 19:58:15.696+0000 [id=1]	INFO	o.e.j.s.handler.ContextHandler#doStart: Started w.@5f9edf14{Jenkins v2.264,/,file:///var/jenkins_home/war/,AVAILABLE}{/var/jenkins_home/war}
2020-11-06 19:58:16.097+0000 [id=1]	INFO	o.e.j.server.AbstractConnector#doStart: Started ServerConnector@366e2eef{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2020-11-06 19:58:16.097+0000 [id=1]	INFO	org.eclipse.jetty.server.Server#doStart: Started @10509ms
2020-11-06 19:58:16.112+0000 [id=23]	INFO	winstone.Logger#logInternal: Winstone Servlet Engine running: controlPort=disabled
2020-11-06 19:58:20.293+0000 [id=27]	INFO	jenkins.InitReactorRunner$1#onAttained: Started initialization
2020-11-06 19:58:26.279+0000 [id=26]	INFO	jenkins.InitReactorRunner$1#onAttained: Listed all plugins
2020-11-06 19:59:28.514+0000 [id=27]	INFO	jenkins.InitReactorRunner$1#onAttained: Prepared all plugins
2020-11-06 19:59:29.081+0000 [id=27]	INFO	jenkins.InitReactorRunner$1#onAttained: Started all plugins
2020-11-06 19:59:51.392+0000 [id=26]	INFO	jenkins.InitReactorRunner$1#onAttained: Augmented all extensions
2020-11-06 19:59:53.754+0000 [id=26]	INFO	jenkins.model.Jenkins#setBuildsAndWorkspacesDir: Using non default workspaces directories: ${JENKINS_HOME}/workspace/${ITEM_FULLNAME}.
2020-11-06 19:59:54.300+0000 [id=26]	INFO	jenkins.InitReactorRunner$1#onAttained: System config loaded
2020-11-06 20:00:11.184+0000 [id=26]	INFO	o.s.c.s.AbstractApplicationContext#prepareRefresh: Refreshing org.springframework.web.context.support.StaticWebApplicationContext@2ee9a06: display name [Root WebApplicationContext]; startup date [Fri Nov 06 20:00:11 UTC 2020]; root of context hierarchy
2020-11-06 20:00:11.185+0000 [id=26]	INFO	o.s.c.s.AbstractApplicationContext#obtainFreshBeanFactory: Bean factory for application context [org.springframework.web.context.support.StaticWebApplicationContext@2ee9a06]: org.springframework.beans.factory.support.DefaultListableBeanFactory@6013c688
2020-11-06 20:00:11.201+0000 [id=26]	INFO	o.s.b.f.s.DefaultListableBeanFactory#preInstantiateSingletons: Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@6013c688: defining beans [authenticationManager]; root of factory hierarchy
2020-11-06 20:00:12.334+0000 [id=26]	INFO	o.s.c.s.AbstractApplicationContext#prepareRefresh: Refreshing org.springframework.web.context.support.StaticWebApplicationContext@65d0d93d: display name [Root WebApplicationContext]; startup date [Fri Nov 06 20:00:12 UTC 2020]; root of context hierarchy
2020-11-06 20:00:12.334+0000 [id=26]	INFO	o.s.c.s.AbstractApplicationContext#obtainFreshBeanFactory: Bean factory for application context [org.springframework.web.context.support.StaticWebApplicationContext@65d0d93d]: org.springframework.beans.factory.support.DefaultListableBeanFactory@1868556f
2020-11-06 20:00:12.335+0000 [id=26]	INFO	o.s.b.f.s.DefaultListableBeanFactory#preInstantiateSingletons: Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@1868556f: defining beans [filter,legacy]; root of factory hierarchy
2020-11-06 20:00:13.316+0000 [id=26]	INFO	o.c.j.p.k.KubernetesClientProvider$SaveableListenerImpl#onChange: Invalidating Kubernetes client: kubernetes null
2020-11-06 20:00:15.405+0000 [id=26]	INFO	jenkins.InitReactorRunner$1#onAttained: System config adapted
2020-11-06 20:00:15.406+0000 [id=27]	INFO	jenkins.InitReactorRunner$1#onAttained: Loaded all jobs
2020-11-06 20:00:15.409+0000 [id=27]	INFO	jenkins.InitReactorRunner$1#onAttained: Configuration for all jobs updated
2020-11-06 20:00:15.781+0000 [id=55]	INFO	hudson.model.AsyncPeriodicWork#lambda$doRun$0: Started Download metadata
2020-11-06 20:00:15.795+0000 [id=55]	INFO	hudson.util.Retrier#start: Attempt #1 to do the action check updates server
2020-11-06 20:00:16.331+0000 [id=27]	INFO	hudson.model.AllView#migrateLegacyPrimaryAllViewLocalizedName: JENKINS-38606 detected for AllView in hudson.model.Hudson@26656a35; renaming view from All to all
2020-11-06 20:00:16.500+0000 [id=27]	INFO	o.s.c.s.AbstractApplicationContext#prepareRefresh: Refreshing org.springframework.web.context.support.StaticWebApplicationContext@72292e32: display name [Root WebApplicationContext]; startup date [Fri Nov 06 20:00:16 UTC 2020]; root of context hierarchy
2020-11-06 20:00:16.504+0000 [id=27]	INFO	o.s.c.s.AbstractApplicationContext#obtainFreshBeanFactory: Bean factory for application context [org.springframework.web.context.support.StaticWebApplicationContext@72292e32]: org.springframework.beans.factory.support.DefaultListableBeanFactory@31a834fe
2020-11-06 20:00:16.504+0000 [id=27]	INFO	o.s.b.f.s.DefaultListableBeanFactory#preInstantiateSingletons: Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@31a834fe: defining beans [filter,legacy]; root of factory hierarchy
2020-11-06 20:00:16.790+0000 [id=27]	INFO	o.c.j.p.k.KubernetesClientProvider$SaveableListenerImpl#onChange: Invalidating Kubernetes client: kubernetes null
2020-11-06 20:00:17.831+0000 [id=27]	INFO	o.c.j.p.k.KubernetesClientProvider$SaveableListenerImpl#onChange: Invalidating Kubernetes client: kubernetes null
2020-11-06 20:00:17.832+0000 [id=27]	INFO	jenkins.InitReactorRunner$1#onAttained: Completed initialization
2020-11-06 20:00:17.891+0000 [id=20]	INFO	o.c.j.p.k.KubernetesClientProvider$SaveableListenerImpl#onChange: Invalidating Kubernetes client: kubernetes null
2020-11-06 20:00:19.189+0000 [id=20]	INFO	hudson.WebAppMain$3#run: Jenkins is fully up and running

The container is breaking after this.....

**Comment by alonsoir** [comment]
It should not be closed because the issue is still happening...
